### ISSUE TITLE
[BUG]: Resolution not correct/not properly detected

### ISSUE THREAD

**Issue by jolumatro** [ikhoeyZX/Vita3K-Android#518]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Affected Build(s)

V12.5 Build 13 / V12.5 Build 12 / V12.5 Build 11

### Description of Issue

The resolution on Anbernic RG505M is not showing correctly: The device has an actual native PSVita display (960x544) and as you can see on the screenshots, it is never centered.

### Expected Behavior

Scaling and presentation to show as 1:1

### Reproduction Steps

Install any version of ikhoeyZX fork on an Anbernic RG505M. Official Vita3K Android fork does not show this issue.

### Log File

Log file is 0 KB

### System Configuration

CPU: Unisoc Tiger T618
GPU/Driver: System driver
RAM: 4GB
OS: GammaOS

![Image](https://github.com/user-attachments/assets/8cce9b46-9a08-44f7-805b-0eaed8541c78)
![Image](https://github.com/user-attachments/assets/12a0ef9c-70de-4a06-92bf-18b29940f415)
![Image](https://github.com/user-attachments/assets/91835304-0bda-4384-9557-2cbcb219c515)

**Comment by jolumatro** [comment]
![Image](https://github.com/user-attachments/assets/e7adfd1c-32a2-4397-92a9-84a1b242fddd)
![Image](https://github.com/user-attachments/assets/0423b0f3-f7ae-4e3a-8aea-b6aa57b638b4)
Comparison between ikhoeyZX and Official fork

**Comment by ikhoeyZX** [comment]
try "clean shader cache"

**Comment by jolumatro** [comment]
Thank you for the reply.

I cleared it before posting here, also switched to OpenGL instead of Vulkan (OpenGL just gives black screen)

**Comment by aarstar** [comment]
I'm having the same issue on my Odin 2. This was actually fixed in the original Vita-Android port, which used to have this issue.

https://github.com/Vita3K/Vita3K-Android/releases/tag/v12
Fix black bands appearing sometimes at the top and bottom of the application on some devices

Don't know more than that, sorry.

Edit: I see that jolumatro already mentioned that this doesn't occur in the official android fork.

**Comment by ikhoeyZX** [comment]
can you test using this build
https://github.com/ikhoeyZX/Vita3K-Android/actions/runs/14958173408

and enable this?
![Image](https://github.com/user-attachments/assets/2ec016b8-c140-4120-b156-92e3d5df01c7)

**Comment by jolumatro** [comment]
Hello!
Thanks for this. It does indeed work:

![Image](https://github.com/user-attachments/assets/23806142-5a04-4405-b160-fdc5396b0d81)
Only thing I have noticed is that the text in SFxT is even more garbled than before, but I will play with the GPU settings to see

![Image](https://github.com/user-attachments/assets/44670439-fefd-4b26-a561-e47e281070ae)

![Image](https://github.com/user-attachments/assets/535465ee-9282-4486-bbaa-a924f921dece)

**Comment by ikhoeyZX** [comment]
as far i know that game still have issue with font in mali gpu (idk why)

**Comment by jolumatro** [comment]
If it helps, it also suffers from issues on my pc with Ryzen (Vulkan) text does not appear or highlight on the menu
What I have tested already is that, no matter what settings I change in GPU in this release, videos (and some screens, like Criware/Autodesk) do not appear

Other than that, the size of the screen is fixed

**Comment by ikhoeyZX** [comment]
yeah,
i think i did made mistake in that build (blue reflection also glichy with that build)
try this instead 
https://github.com/ikhoeyZX/Vita3K-Android/actions/runs/14952095580

**Comment by jolumatro** [comment]
Hello, thanks for this!

Yes, splash screens and initial video are fixed, as well as the scaling issue, but videos when going in arcade mode play weird or with the previous buffered image from the initial video.

In any case, great work, man!

**Comment by ikhoeyZX** [comment]
fixed in next update
